name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      - name: Build Python distribution
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
      - name: Bump version
        run: echo "${{ github.ref }}" | sed -E 's/refs\/tags\///' > VERSION
      - name: Commit version
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Bump version"
          git push origin
