name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: change version
        run: |
            tag_name=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
            echo $tag_name > ../../VERSION
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      - name: Build Python distribution
        run: python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
